### PR TITLE
make request without Dbname like BitSetCheckedAuthorizationProvider#a…

### LINKED ISSUE #158: BitSetCheckedAuthorizationProvider#authorizeUserPriv without DbName  cannot contact to waggle-dance
when using BitSetCheckedAuthorizationProvider to do authorization, the dbname is null. Waggle dance cannot process the request.

protected boolean authorizeUserPriv(Privilege[] inputRequiredPriv,
      boolean[] inputCheck, Privilege[] outputRequiredPriv,
      boolean[] outputCheck) throws HiveException {
    PrincipalPrivilegeSet privileges = hive_db.get_privilege_set(
        HiveObjectType.GLOBAL, null, null, null, null, this.getAuthenticator()
            .getUserName(), this.getAuthenticator().getGroupNames());
    return authorizePrivileges(privileges, inputRequiredPriv, inputCheck,
        outputRequiredPriv, outputCheck);
  }

I think waggle dance can change to 

public PrincipalPrivilegeSet get_privilege_set(HiveObjectRef hiveObject, String user_name, List<String> group_names)
    throws MetaException, TException {
    DatabaseMapping mapping;

    if(hiveObject.getDbName().equals(null)){
      mapping = databaseMappingService.primaryDatabaseMapping();
    }else{
      mapping = databaseMappingService.databaseMapping(hiveObject.getDbName());
    }

    return mapping.getClient().get_privilege_set(mapping.transformInboundHiveObjectRef(hiveObject), user_name,
        group_names);
  }

### PR DESCRIPTION
**Pull request by Elvis0607**
This is corresponding and fixes #158. 
I have used the code in our test cluster

### CODE REVIEW

File: waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/server/FederatedHMSHandler.java [hunk 1]
```diff
@@ -1157,10 +1157,18 @@ public GetRoleGrantsForPrincipalResponse get_role_grants_for_principal(GetRoleGr
...
       throws MetaException, TException {
-    DatabaseMapping mapping = databaseMappingService.databaseMapping(hiveObject.getDbName());
-    return mapping
-        .getClient()
-        .get_privilege_set(mapping.transformInboundHiveObjectRef(hiveObject), user_name, group_names);
+    DatabaseMapping mapping;
+    HiveObjectRef hiveObjectResult;
+    if (hiveObject.getDbName() == null) {
+      mapping = databaseMappingService.primaryDatabaseMapping();
+      hiveObjectResult = hiveObject;
```
Comment (patduin) [inline waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/server/FederatedHMSHandler.java]: you'll need to transform the object for this mapping as well (it works like this but will be more future proof if we transform, probably easiest to remove the `hiveObjectResult` field and change the return to the original:
```
mapping.getClient().get_privilege_set(mapping.transformInboundHiveObjectRef(hiveObject), user_name, group_names);
```

Comment (Elvis0607) [reply waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/server/FederatedHMSHandler.java]: I have change the code like this 

public PrincipalPrivilegeSet get_privilege_set(HiveObjectRef hiveObject, String user_name, List<String> group_names)
      throws MetaException, TException {
    DatabaseMapping mapping;
    if (hiveObject.getDbName() == null) {
      mapping = databaseMappingService.primaryDatabaseMapping();
    } else {
      mapping = databaseMappingService.databaseMapping(hiveObject.getDbName());
    }
    return mapping.getClient().get_privilege_set(mapping.transformInboundHiveObjectRef(hiveObject), user_name,
            group_names);
  }
