### PR TITLE
using dummy client if connection unavailable

### LINKED ISSUE #80: Waggle Dance fails to serve when destination bastion is down/unreachable
**Issue:**
Waggle Dance federates to primary Metasotre `A` and foreign Metastore `B` (over SSH Tunnel through bastion host `BH`).
If for any reason, `BH` is down/unreachable or disallow SSH connection then this cause whole WD to stops serving request even for Metastore `A`.

**Excepted Behaviour:**
WD to handle the above situation gracefully and continue to serve rest of the Metastores.

**Current Behaviour:**
WD fails to serve all requests.

### PR DESCRIPTION
**Pull request by patduin**
fixes #80

### CODE REVIEW

File: waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java [hunk 1]
```diff
@@ -63,4 +73,34 @@ public String prefixNameFor(AbstractMetaStore federatedMetaStore) {
...
+
+    private UnreachableMetastoreClientInvocationHandler(String name) {
+      this.name = name;
+    }
+
+    @Override
+    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
+      switch (method.getName()) {
+      case "isOpen":
+        return false;
```
Comment (massdosage) [inline waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java]: Does this mean later on WD will think this thing is closed and try create a new one and attempt a reconnect? I'm just trying to think about the sequence of events here - while the remote is unreachable how often will it check that it's back and then recover?

File: waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java [hunk 2]
```diff
@@ -63,4 +73,34 @@ public String prefixNameFor(AbstractMetaStore federatedMetaStore) {
...
+      case "close":
+        return null;
+      default:
+        throw new TException("Metastore `" + name + "` unavailable");
```
Comment (massdosage) [inline waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java]: Can we please use ' instead of ` ?

File: waggle-dance-core/src/test/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImplTest.java [hunk 3]
```diff
@@ -96,4 +97,18 @@ public void connectionLost() throws Exception {
...
+    MetaStoreMappingFactoryImpl factory = new MetaStoreMappingFactoryImpl(prefixNamingStrategy,
+        closeableThriftHiveMetastoreIfaceClientFactory, accessControlHandlerFactory);
+    AbstractMetaStore federatedMetaStore = newFederatedInstance("fed1", thrift.getThriftConnectionUri());
+    when(closeableThriftHiveMetastoreIfaceClientFactory.newInstance(federatedMetaStore))
+        .thenThrow(new RuntimeException("Cannot create client"));
+
+    MetaStoreMapping mapping = factory.newInstance(federatedMetaStore);
+    assertThat(mapping, is(notNullValue()));
+    assertThat(mapping.isAvailable(), is(false));
+  }
```
Comment (massdosage) [inline waggle-dance-core/src/test/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImplTest.java]: If the idea is that at some point the failure can be recovered from it would be good to have a test showing the sequence of events and the recovery happening.

File: waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java (hunk 1 above)
Comment (patduin) [reply waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java]: User(hive/spark client) opens a session does a request for the duration of that session this client lives. So if you do a query (show databases) it won't show databases for the broken metastore. If you do a query on the specific database in that metastore (prefix and all) it will fail like hive would fail if you try to query a database that doesn't exist. 
If you close your client and reconnect it will check all metastores again.

File: waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java (hunk 2 above)
Comment (patduin) [reply waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java]: oh `yes`

File: waggle-dance-core/src/test/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImplTest.java (hunk 3 above)
Comment (patduin) [reply waggle-dance-core/src/test/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImplTest.java]: you need to create a new instance, that's a bit silly to test in this method

File: waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java (hunk 1 above)
Comment (massdosage) [reply waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java]: OK, makes sense, so for a call to a Thrift method it will create one of these, the specific method call will throw the below exception which WD will log and ignore and this will carry on until you reconnect at which point it will attempt to connect again etc.

File: waggle-dance-core/src/test/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImplTest.java (hunk 3 above)
Comment (massdosage) [reply waggle-dance-core/src/test/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImplTest.java]: OK, yeah, I understand the lifecycle better now.

File: waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java [hunk 4]
```diff
@@ -63,4 +73,34 @@ public String prefixNameFor(AbstractMetaStore federatedMetaStore) {
...
+
+    @Override
+    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
+      switch (method.getName()) {
+      case "isOpen":
+        return false;
+      case "close":
+        return null;
+      default:
+        throw new TException("Metastore '" + name + "' unavailable");
```
Comment (massdosage) [inline waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java]: Can you write a test for this behaviour?

File: waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java (hunk 1 above)
Comment (patduin) [reply waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java]: yes, you have to reconnect. If you are doing multiple queries inside the hive-client it will use the disconnected one.

File: waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java (hunk 4 above)
Comment (massdosage) [reply waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java]: Ah, OK, right, makes sense. Thanks for the explanation.

File: waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java [hunk 5]
```diff
@@ -63,4 +73,34 @@ public String prefixNameFor(AbstractMetaStore federatedMetaStore) {
...
+    return (CloseableThriftHiveMetastoreIface) Proxy.newProxyInstance(getClass().getClassLoader(),
+        new Class[] { CloseableThriftHiveMetastoreIface.class },
+        new UnreachableMetastoreClientInvocationHandler(metaStore.getName()));
+  }
+
+  /**
+   * Handler that refuses to be open and will throw exceptions for any of the methods, serves as a dummy client if the
+   * real one can't be created due to connection (i.e. tunneling) issues.
+   */
+  private static class UnreachableMetastoreClientInvocationHandler implements InvocationHandler {
```
[the remark this answers is not in the document]
Comment (patduin) [reply waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/mapping/model/MetaStoreMappingFactoryImpl.java]: yes it has no business being used anywhere else
